package agentdecl

// Code generated by tools/preseed-hashes. DO NOT EDIT.
//
// blessedPreseedHashes holds the sha256 of every version of every shipped
// declaration this tree has committed. A seeded copy matching one of them is a
// release's, not the operator's, so seeding refreshes it to the current version.
var blessedPreseedHashes = map[string][]string{
	"agents.toml": {
		"6f5b53c154c051424c531bd535858b6b1e56f4b81aae6489302ddf47359d2e34",
		"1388977981cd067d39fc8e625763b931f5369c0134db96cbee82c08f4fa0aee8",
		"f8e43c5df48a8606d43661da60e2b069635fd100266a9cbb5bf2d6b189de5387",
		"1c28c88f5336aa46fd123bb37422392414352c764ea9b29172ba90d91a578a76",
		"4762a10692ded686937627d61d23afd6591f6b87325fe94990c75ba2acffe641",
		"c8e9da83ffdae4e9d7304010208608de8b87b9baf00bdd4cf24c1a81e4546ddf",
		"42851d2325da04d152cacff5a93c13f5baeecd6eccde6cad6577bafa5fc624da",
	},
	"agents/README.md": {
		"a04060f1e846a2988d30c8fc7ccc7e85cf9d1a7551a99fb6169e4aec75d4afb4",
		"d06af8431759fd00ddc10d651d21d7e995e60d9127b69450768af5de1433bdef",
	},
	"agents/acp/agent.md": {
		"dbc70bcf07a6f1cd6601d83968d6d5fb4856169abe8628b76eef71d2f9555064",
		"764ab97f5a803a248708782f9470547fee884c5a12a8af7acb11a025a6c09725",
	},
	"agents/acp/coding/agent.md": {
		"fb72684a8e938269686b9d604a794f6d19dc4a7f35a6e970381748a11217a923",
		"56eef8e867e81e99573d489eb59e07492d6f8be8e764b83dd240df23584afe5b",
		"145704f914f5b2144ac0335eb9b4bfa6d8d0a2af49d6a667679446500ef8f444",
		"4a928e566606eab7e026fc40a9ee7b5005d9d554d113c38c534a65e6d8cfb15f",
		"0e4268d475c561b03ebc61c0f2d12099cbd0db8efd323322d8764c350d93c25a",
	},
	"agents/acp/coding/recovery.md": {
		"3dbcceb70a1e2850971145b77e53b3daa4466f64bdd8b45b27a0e7179ad0840d",
		"6f0c4f55e2858981f067c955231a6edc48c7ed6d60a5e71d4766707a2acab6b1",
		"eff0e05baeecf8aa877e7a7f538903bc93535e31d6ea7f45d5c14179ace631e1",
		"1d453d050ae5a3e373db76460f1c7537b069b22fc8f4d291c02f1096f50b5713",
	},
	"agents/acp/failure.md": {
		"85bdb3b48aff225e9d3edc80912a9680fd8c3e6d7ed67d1456e6b8e10fa78629",
	},
	"agents/acp/general/agent.md": {
		"30875d0f1204583b4cdcae490af3a4c6eed506aa5c685b6be2311049a7b15055",
		"4db7583c6c1160bc1a21918ddbb222d33ae18f249a347dc820b535086db03295",
		"46f2034b8f0feda6462d1781480be0a95ba934638ae7b9e2bd5f5bc63ce42c13",
		"011d055c16a89f247387f40220c216431a90ee5968ce8ce3c2bb1599a61d8168",
		"6c3f34a8db95baef52c6309043b2589e78a1776d86fc415b007e58acb0f595d8",
	},
	"agents/acp/general/recovery.md": {
		"8c158c27cca4ffa4fb42825fa1bc7f8622a8f65af8a2446824fdf4fdaf785328",
		"c3b1f049d07561dd3674c5d0fadf524425116df4ace95443d401ed17e26124cf",
		"1bf1782b077fe575de968a21f060b463cfef9277f339709172a448f918880c1a",
		"64eb3fce30b39c35a16eda612cf84797495882dd82ee5da1fd016452ef56e860",
	},
	"agents/acp/review/agent.md": {
		"63105b39efbbc6cbbf81fd9bfeb4c8f2fcb12a25c9d49c9eaa89ac7bdb3b9a8d",
		"e25d24d152f47ad4d6bc24a7b81ab59f38aa4910990a4e7a318591e5fa8fb709",
		"1eb8799bdb42c5b0d0199e0607be400a92be9384cffa665f05bec48d3405bd4f",
		"f54d1f43d20d48d720207494f09d98c65804806d2e734a712c48638cea099a00",
	},
	"agents/acpx.md": {
		"9b1d876ba7987a343c1c766fc7e9b4a47ba007852fd52a7124c17329f0dd5763",
		"4590684651f22d39955572a8dcc9b74d87b599aaac2c112b42eb4bb7d321ccff",
		"4cfdb4d16a11bb4b466f6882e4f1e7abecc3ff6a47c44e0656bd340e51b7edee",
		"fefee9ba8d81317529ca67a5c36ec6b91b6f4535dde7be5557659d032c3d1743",
	},
	"agents/change/agent.md": {
		"5993c0e0e5e1dc951c8fb0c0e8ed3128a7d671400c493eb7ca7dc07389d6f3fe",
	},
	"agents/change/review/agent.md": {
		"380db24a8939b81efaffe8af3d02dafe37c830d47a398fbdc28cce65385d704c",
	},
	"agents/change/risk/agent.md": {
		"adb87b8270f50cea9e50c28b24f95309f0b3af2feb6a34269639bc3a15d86680",
	},
	"agents/chat.md": {
		"4706bc96ed07bd3bfdef59729a3e342155bc7fe713063828727f8530e197771b",
	},
	"agents/researcher.md": {
		"35c1002c7c86c8509ad974312dfa43b8bae44fc446c28d1ec8bc8fb793f1a11c",
	},
	"agents/reviewer.md": {
		"0aa955fa9ec4f9350ff080d247ad72903a1a078c2561626da8882728ffdc0694",
	},
	"agents/run.md": {
		"73d4dec4896d783d1d43a29d9f9b222d8c19837a6cb9c4c8cbb3e0f40bbe5d94",
		"5dfe1b0309ec6a26e46bfadf6bdb8c013993c02b5b1da3ad5d17813858c58003",
	},
	"agents/triage/agent.md": {
		"0d337ef8d1f22eca62741bab7783b0d758d10c5e64b403724171e1c6af85c6b0",
	},
	"agents/triage/code/agent.md": {
		"05a63ee70196b72a2a4ed95186d6ef2ade58fbad7129808378a60e3328d39fc5",
		"4bb8cd498f5221d283f57cff5206e56124bb63837206d82e3e686c77d0ee41be",
	},
	"agents/triage/code/recovery.md": {
		"cb083f42ef1610618bc2806d43b39d7b6b044adde863ae5ab2058c373cabead5",
	},
	"agents/triage/docs/agent.md": {
		"fa1f9ef93478c352c0d1cba5867ce09037b8ec623ff1d35357441732958952e4",
	},
}
