// Command preseed-hashes writes the blessed-hash table agentdecl reads when
// deciding whether a seeded declaration on disk is still the release's to
// refresh.
//
// A copy that matches a version this tree ever committed is ours, whatever
// release wrote it, so every committed version of every shipped source belongs
// in the table. Seeding calls it blessed and refreshes the copy; without it, an
// install from an earlier release is indistinguishable from a file the operator
// authored, and would be left behind forever.
//
// Run it from this tree's root whenever a shipped declaration changes:
//
//	go run ./tools/preseed-hashes
//
// `task preseed:hashes` runs the same command. A path this tree renamed drops
// out of the table — git history is read at the path the file has now — so a
// rename needs the table regenerated and the copy on disk refreshed by hand
// once, or it reads as an operator's file from then on.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/contenox/contenox/internal/services/agentdecl"
)

const (
	pkgDir  = "internal/services/agentdecl"
	outFile = "internal/services/agentdecl/preseed_blessed.go"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "preseed-hashes: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	out, err := git("rev-parse", "--show-toplevel")
	if err != nil {
		return err
	}
	root := strings.TrimSpace(string(out))
	abs, err := filepath.Abs(pkgDir)
	if err != nil {
		return err
	}
	pkgRel, err := filepath.Rel(root, abs)
	if err != nil {
		return err
	}
	sources, err := agentdecl.PreseedSources()
	if err != nil {
		return err
	}
	table := make(map[string][]string, len(sources))
	for _, source := range sources {
		gitPath := path.Join(filepath.ToSlash(pkgRel), source.Source)
		hashes, err := history(root, gitPath)
		if err != nil {
			return err
		}
		if len(hashes) == 0 {
			return fmt.Errorf("%s has no committed history; a shipped declaration must be committed before it can be blessed", gitPath)
		}
		// The working copy is blessed too: an edit is then recognised as ours
		// both before it is committed and after, so the table never has to be
		// regenerated in the same breath as the change that made it stale.
		current, err := os.ReadFile(filepath.Join(pkgDir, filepath.FromSlash(source.Source)))
		if err != nil {
			return err
		}
		sum := sha256.Sum256(current)
		table[source.Rel] = withHash(hashes, hex.EncodeToString(sum[:]))
	}
	src, err := render(table)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s: %d declarations\n", outFile, len(table))
	return nil
}

func withHash(hashes []string, hash string) []string {
	for _, have := range hashes {
		if have == hash {
			return hashes
		}
	}
	return append(hashes, hash)
}

// history is every distinct content this path ever held, newest first. Paths are
// read from the repository root: a pathspec is relative to the working
// directory, and this runs from whichever directory the command was started in.
func history(root, gitPath string) ([]string, error) {
	commits, err := git("-C", root, "log", "--all", "--format=%H", "--", gitPath)
	if err != nil {
		return nil, err
	}
	var hashes []string
	seen := map[string]bool{}
	for _, commit := range strings.Fields(string(commits)) {
		blob, err := git("-C", root, "show", commit+":"+gitPath)
		if err != nil {
			continue
		}
		sum := sha256.Sum256(blob)
		hash := hex.EncodeToString(sum[:])
		if seen[hash] {
			continue
		}
		seen[hash] = true
		hashes = append(hashes, hash)
	}
	return hashes, nil
}

func render(table map[string][]string) ([]byte, error) {
	rels := make([]string, 0, len(table))
	for rel := range table {
		rels = append(rels, rel)
	}
	sort.Strings(rels)

	var buf bytes.Buffer
	buf.WriteString(`package agentdecl

// Code generated by tools/preseed-hashes. DO NOT EDIT.
//
// blessedPreseedHashes holds the sha256 of every version of every shipped
// declaration this tree has committed. A seeded copy matching one of them is a
// release's, not the operator's, so seeding refreshes it to the current version.
var blessedPreseedHashes = map[string][]string{
`)
	for _, rel := range rels {
		fmt.Fprintf(&buf, "\t%q: {\n", rel)
		for _, hash := range table[rel] {
			fmt.Fprintf(&buf, "\t\t%q,\n", hash)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return format.Source(buf.Bytes())
}

func git(args ...string) ([]byte, error) {
	cmd := exec.Command("git", args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git %s: %v: %s", strings.Join(args, " "), err, strings.TrimSpace(stderr.String()))
	}
	return out, nil
}
