package modelregistry

import "github.com/contenox/contenox/internal/modeld/capacity"

const (
	toolProtocolLlamaCommonChat             = "llama:common_chat_tool_parser"
	toolProtocolOpenVINOJSONSchemaToolCalls = "openvino:json_schema_tool_calls"
	reasoningProtocolLlamaCommonChat        = "llama:common_chat_reasoning_parser"
	reasoningFormatDeepSeek                 = "deepseek"
	useCaseChat                             = "chat"
	// AgenticTierAgentic marks a model evidenced to run a multi-step tool loop;
	// automatic selection picks nothing below it.
	AgenticTierAgentic = "agentic"
	// AgenticTierToolChat marks a model that calls tools but is not evidenced to
	// sustain a loop: fine for a smoke test or a one-shot question, not for an
	// agent working a task.
	AgenticTierToolChat = "tool-chat"
	// AgenticTierNone marks a model whose template the runtime cannot read calls
	// from, whatever its card claims.
	AgenticTierNone  = "none"
	useCaseCoding    = "coding"
	useCaseReasoning = "reasoning"
	useCaseSmoke     = "smoke"
)

var curatedModels = map[string]ModelDescriptor{
	"qwen3.8-27b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Qwen tool-calling family at 27B dense; the current generation has no published multi-turn row, so the tier rests on family provenance and the setup probe",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 64, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "qwen3.8-27b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3.8-27B-GGUF/resolve/4ca720788d1e01f1bff70c033e0d0028fd02e502/Qwen3.8-27B-UD-Q4_K_M.gguf",
		SizeBytes:         16464440224,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-08-14",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3.8",
		DisplayLabel:      "Qwen 3.8 27B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 24,
		Notes:             "Text only; parser supported, not runtime-certified",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"qwen3.5-0.8b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "smoke-test class: sub-1B does not clear multi-turn tool use in any measured suite (BFCL v4 multi-turn <=3.62%)",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 24, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 2048},
		Name:              "qwen3.5-0.8b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/6ab461498e2023f6e3c1baea90a8f0fe38ab64d0/Qwen3.5-0.8B-Q4_K_M.gguf",
		SizeBytes:         532517120,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-03-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3.5",
		DisplayLabel:      "Qwen 3.5 0.8B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 2,
		Notes:             "Text only; parser supported, not runtime-certified",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"qwen3.5-2b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "below the multi-step floor: BFCL v4 multi-turn is 0.00-3.62% under 2B, and the best sub-2B result is a two-tool chain",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 24, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 2048},
		Name:              "qwen3.5-2b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/f6d5376be1edb4d416d56da11e5397a961aca8ae/Qwen3.5-2B-Q4_K_M.gguf",
		SizeBytes:         1280835840,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-03-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3.5",
		DisplayLabel:      "Qwen 3.5 2B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 3,
		Notes:             "Text only; parser supported, not runtime-certified",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"qwen3.5-4b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  ">=3B with Qwen tool-training provenance; the official 4B-class BFCL v4 multi-turn row is 22.12%",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 32, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "qwen3.5-4b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/e87f176479d0855a907a41277aca2f8ee7a09523/Qwen3.5-4B-Q4_K_M.gguf",
		SizeBytes:         2740937888,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-03-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3.5",
		DisplayLabel:      "Qwen 3.5 4B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 5,
		Notes:             "Text only; parser supported, not runtime-certified",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"qwen3.5-9b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Qwen XML tool template; vendor-reported BFCL v4 66.1 and tau2 79.1, the strongest sub-10B vendor claim; no independent row exists",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 32, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "qwen3.5-9b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/3885219b6810b007914f3a7950a8d1b469d598a5/Qwen3.5-9B-Q4_K_M.gguf",
		SizeBytes:         5680522464,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-03-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3.5",
		DisplayLabel:      "Qwen 3.5 9B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
		Notes:             "Text only; parser supported, not runtime-certified",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"ministral3-3b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "no published multi-turn evidence at 3B; probe required before it can be picked automatically",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 26, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "ministral3-3b",
		SourceURL:         "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/eb599d408350ea2bb60452cb86be7c7b2fc28227/Ministral-3-3B-Instruct-2512-Q4_K_M.gguf",
		SizeBytes:         2147023008,
		Curated:           true,
		Origin:            "eu",
		ReleasedAt:        "2025-12-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "ministral3",
		DisplayLabel:      "Ministral 3 3B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 4,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	"ministral3-8b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "joint-best sub-10B two-tool chain in AgentFloor (84%), matching qwen3:14b",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 34, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "ministral3-8b",
		SourceURL:         "https://huggingface.co/mistralai/Ministral-3-8B-Instruct-2512-GGUF/resolve/0102285ad796bd99af90f58de616092e5630e970/Ministral-3-8B-Instruct-2512-Q4_K_M.gguf",
		SizeBytes:         5198911904,
		Curated:           true,
		Origin:            "eu",
		ReleasedAt:        "2025-12-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "ministral3",
		DisplayLabel:      "Ministral 3 8B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	"ministral3-14b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Ministral 3 tool template; the larger sibling of the joint-best sub-10B two-tool chain",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 40, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "ministral3-14b",
		SourceURL:         "https://huggingface.co/mistralai/Ministral-3-14B-Instruct-2512-GGUF/resolve/74fac473c43357d7fb2671713608183cc72496d0/Ministral-3-14B-Instruct-2512-Q4_K_M.gguf",
		SizeBytes:         8239593024,
		Curated:           true,
		Origin:            "eu",
		ReleasedAt:        "2025-12-02",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "ministral3",
		DisplayLabel:      "Ministral 3 14B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 12,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	"gigachat3.1-10b-a1.8b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "no published multi-turn tool-use evidence; probe required before it can be picked automatically",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 26, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 24576},
		Name:              "gigachat3.1-10b-a1.8b",
		SourceURL:         "https://huggingface.co/ai-sage/GigaChat3.1-10B-A1.8B-GGUF/resolve/97045b260251cfa86f5ad25638fa2dd074153446/GigaChat3.1-10B-A1.8B-q4_K_M.gguf",
		SizeBytes:         6474702976,
		Curated:           true,
		Origin:            "gus",
		ReleasedAt:        "2026-03-24",
		License:           "mit",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gigachat3.1",
		DisplayLabel:      "GigaChat 3.1 Lightning",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 10,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	// The 6 GB class: 3B and below at a KV geometry a small card can afford,
	// added because the agentic tier otherwise starts at ~5 GB of weights and a
	// 6 GB device was told to buy a bigger machine.
	"nanbeige4-3b-thinking": {
		AutoContextLimit: 65536, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 32, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 2048},
		Name:              "nanbeige4-3b-thinking",
		SourceURL:         "https://huggingface.co/bartowski/Nanbeige_Nanbeige4-3B-Thinking-2511-GGUF/resolve/main/Nanbeige_Nanbeige4-3B-Thinking-2511-Q4_K_M.gguf",
		ChatTemplateURL:   "https://huggingface.co/Nanbeige/Nanbeige4-3B-Thinking-2511/raw/main/tokenizer_config.json",
		SizeBytes:         2443112896,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2025-11-30",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "nanbeige4",
		DisplayLabel:      "Nanbeige 4 3B Thinking",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
		AgenticTier:       AgenticTierAgentic,
		AgenticEvidence:   "official BFCL v4: overall 51.40%, multi-turn 51.12% — the highest overall score on that board among sub-10B models",
		Notes:             "text only; Hermes JSON tool dialect; thinking mode",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"minicpm5-2b": {
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 42, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 1024},
		Name:              "minicpm5-2b",
		SourceURL:         "https://huggingface.co/openbmb/MiniCPM5-2B-GGUF/resolve/main/MiniCPM5-2B-Q4_K_M.gguf",
		ChatTemplateURL:   "https://huggingface.co/openbmb/MiniCPM5-2B/raw/main/chat_template.jinja",
		SizeBytes:         1561318368,
		Curated:           true,
		Origin:            "china",
		ReleasedAt:        "2026-09-07",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "minicpm5",
		DisplayLabel:      "MiniCPM5 2B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
		AgenticTier:       AgenticTierAgentic,
		AgenticEvidence:   "vendor-reported BFCL v4 66.6 of a 2B; no official board row exists for this generation, so the setup probe is the certification",
		Notes:             "text only; XML <function name=…> tool dialect; thinking mode",
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
	},
	"granite4.1-3b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "the 3B tier carries no agentic RL in Granite 4.x; single-shot tool calls only until a probe says otherwise",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 40, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 2048},
		Name:              "granite4.1-3b",
		SourceURL:         "https://huggingface.co/ibm-granite/granite-4.1-3b-GGUF/resolve/ab4701481089b58a082ef63cc1cee738887293ff/granite-4.1-3b-Q4_K_M.gguf",
		SizeBytes:         2099501664,
		Curated:           true,
		Origin:            "us",
		ReleasedAt:        "2026-04-29",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "granite4.1",
		DisplayLabel:      "Granite 4.1 3B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 4,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	"granite4.1-8b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Granite 4.x agentic RL tier; served through the Qwen XML tool dialect, unlike 4.0's Hermes JSON",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 40, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "granite4.1-8b",
		SourceURL:         "https://huggingface.co/ibm-granite/granite-4.1-8b-GGUF/resolve/865b82c2e7970d82e3731278c88c57ae7138359c/granite-4.1-8b-Q4_K_M.gguf",
		SizeBytes:         5347914400,
		Curated:           true,
		Origin:            "us",
		ReleasedAt:        "2026-04-29",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "granite4.1",
		DisplayLabel:      "Granite 4.1 8B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
		Notes:             "Text only; parser supported, not runtime-certified",
	},
	"granite4.1-30b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Granite 4.x agentic reinforcement learning applies to the 8B and 30B tiers",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 64, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Name:              "granite4.1-30b",
		SourceURL:         "https://huggingface.co/ibm-granite/granite-4.1-30b-GGUF/resolve/26a44ffe9923eea39af3ad811b56c9b0071e4347/granite-4.1-30b-Q4_K_M.gguf",
		SizeBytes:         17490240736,
		Curated:           true,
		Origin:            "us",
		ReleasedAt:        "2026-04-29",
		License:           "apache-2.0",
		AutoEligible:      true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "granite4.1",
		DisplayLabel:      "Granite 4.1 30B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 24,
		Notes:             "Text only; parser supported, not runtime-certified",
	},

	// ── Qwen 3 ───────────────────────────────────────────────────────────────
	"qwen3-4b": {
		Name:              "qwen3-4b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
		SizeBytes:         2_497_280_256,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "qwen3",
		DisplayLabel:      "Qwen 3 4B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
	},
	"qwen3-8b": {
		Name:              "qwen3-8b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf",
		SizeBytes:         5_027_783_488,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "qwen3",
		DisplayLabel:      "Qwen 3 8B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
	},
	"qwen3-14b": {
		Name:              "qwen3-14b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen3-14B-GGUF/resolve/main/Qwen3-14B-Q4_K_M.gguf",
		SizeBytes:         9_001_752_960,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "qwen3",
		DisplayLabel:      "Qwen 3 14B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 16,
	},
	"qwen3-30b": {
		Name:              "qwen3-30b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen3-30B-A3B-GGUF/resolve/main/Qwen3-30B-A3B-Q4_K_M.gguf",
		SizeBytes:         18_556_685_824,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "qwen3",
		DisplayLabel:      "Qwen 3 30B-A3B",
		UseCase:           useCaseReasoning,
		RecommendedVRAMGB: 32,
		Notes:             "MoE",
	},
	"qwen3-coder-30b-a3b": {
		Name:              "qwen3-coder-30b-a3b",
		SourceURL:         "https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
		SizeBytes:         18_556_689_568,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "qwen3-coder",
		DisplayLabel:      "Qwen 3 Coder 30B-A3B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 32,
		Notes:             "MoE",
	},
	// ── Qwen 2.5 Coder ──────────────────────────────────────────────────────
	"qwen2.5-coder-0.5b": {
		Name:              "qwen2.5-coder-0.5b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen2.5-Coder-0.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-0.5b-instruct-q4_k_m.gguf",
		SizeBytes:         491_400_064,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 0.5B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
		Notes:             "tiny coding smoke test",
	},
	"qwen2.5-coder-1.5b": {
		Name:              "qwen2.5-coder-1.5b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf",
		SizeBytes:         1_117_320_768,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 1.5B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
		Notes:             "small coding model",
	},
	"qwen2.5-coder-3b": {
		Name:              "qwen2.5-coder-3b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen2.5-Coder-3B-Instruct-GGUF/resolve/main/qwen2.5-coder-3b-instruct-q4_k_m.gguf",
		SizeBytes:         2_104_932_800,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 3B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
	},
	"qwen2.5-coder-7b": {
		Name:              "qwen2.5-coder-7b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf",
		SizeBytes:         4_683_073_536,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 7B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 8,
		Notes:             "coding default",
	},
	"qwen2.5-coder-14b": {
		Name:              "qwen2.5-coder-14b",
		SourceURL:         "https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct-GGUF/resolve/main/qwen2.5-coder-14b-instruct-q4_k_m.gguf",
		SizeBytes:         8_988_110_272,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 14B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 16,
	},
	"qwen2.5-coder-32b": {
		Name:              "qwen2.5-coder-32b",
		SourceURL:         "https://huggingface.co/bartowski/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
		SizeBytes:         19_851_336_672,
		Curated:           true,
		Family:            "qwen2.5-coder",
		DisplayLabel:      "Qwen 2.5 Coder 32B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 32,
		Notes:             "large dense coding",
	},
	// ── Google Gemma 4 ───────────────────────────────────────────────────────
	// Multimodal (text+image). The llama entries pair the model GGUF with its
	// multimodal projector (mmproj); llama.cpp serves Gemma 4 vision through the
	// standard model.gguf + mmproj.gguf mtmd path. File names, sizes, and
	// availability verified against the ggml-org HF repos on 2026-07-22 (repos
	// ship BF16/Q4_0/Q8_0 quants — no Q4_K_M — plus mmproj-*-{BF16,Q8_0}.gguf).
	"gemma4-e2b": {
		AgenticTier:      AgenticTierToolChat,
		AgenticEvidence:  "e2b class: single-shot tool use, no multi-step evidence",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 7, WindowedLayers: 28, Window: 512, PerLayerKVBytes: 2048},
		Origin: "us", ReleasedAt: "2026-04-02", License: "apache-2.0", AutoEligible: true,
		Name:              "gemma4-e2b",
		SourceURL:         "https://huggingface.co/ggml-org/gemma-4-E2B-it-GGUF/resolve/b4243c156154b6dca9324415f8c7ccc098b4aed1/gemma-4-E2B-it-Q8_0.gguf",
		SizeBytes:         4_967_497_152,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gemma4",
		DisplayLabel:      "Gemma 4 E2B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
		Vision:            true,
		MMProjURL:         "https://huggingface.co/ggml-org/gemma-4-E2B-it-GGUF/resolve/b4243c156154b6dca9324415f8c7ccc098b4aed1/mmproj-gemma-4-E2B-it-Q8_0.gguf",
		MMProjSizeBytes:   557_368_064,
	},
	"gemma4-e4b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Gemma 4 native tool format, with the template-level tool-loop fix; the only entry noted as native tool format",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 7, WindowedLayers: 35, Window: 512, PerLayerKVBytes: 4096},
		Origin: "us", ReleasedAt: "2026-04-02", License: "apache-2.0", AutoEligible: true,
		Name:              "gemma4-e4b",
		SourceURL:         "https://huggingface.co/ggml-org/gemma-4-E4B-it-GGUF/resolve/b8093469224f83f5c38f691eb906c380e9e63114/gemma-4-E4B-it-Q4_0.gguf",
		SizeBytes:         4_590_807_392,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gemma4",
		DisplayLabel:      "Gemma 4 E4B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
		Vision:            true,
		MMProjURL:         "https://huggingface.co/ggml-org/gemma-4-E4B-it-GGUF/resolve/b8093469224f83f5c38f691eb906c380e9e63114/mmproj-gemma-4-E4B-it-Q8_0.gguf",
		MMProjSizeBytes:   559_874_816,
		Notes:             "native tool format",
	},
	"gemma4-12b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Gemma 4's template fixes tool loops and turn closure",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 8, WindowedLayers: 40, Window: 1024, PerLayerKVBytes: 8192},
		Origin: "us", ReleasedAt: "2026-06-03", License: "apache-2.0", AutoEligible: true,
		Name:              "gemma4-12b",
		SourceURL:         "https://huggingface.co/ggml-org/gemma-4-12B-it-GGUF/resolve/e3e681731089efaa3f0917336944ac64752db8ba/gemma-4-12B-it-Q4_0.gguf",
		SizeBytes:         7_219_673_216,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gemma4",
		DisplayLabel:      "Gemma 4 12B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 12,
		Vision:            true,
		MMProjURL:         "https://huggingface.co/ggml-org/gemma-4-12B-it-GGUF/resolve/e3e681731089efaa3f0917336944ac64752db8ba/mmproj-gemma-4-12B-it-Q8_0.gguf",
		MMProjSizeBytes:   158_987_616,
	},
	// Deliberately text-only: the 26B-A4B/31B mmproj aborts on CUDA upstream
	// (llama.cpp issue #21402) — no projector until that is fixed and verified
	// at our pin.
	"gemma4-26b-a4b": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Gemma 4's template fixes tool loops and turn closure; MoE at 26B total",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 5, WindowedLayers: 25, Window: 1024, PerLayerKVBytes: 8192},
		Origin: "us", ReleasedAt: "2026-04-02", License: "apache-2.0", AutoEligible: true,
		Name:              "gemma4-26b-a4b",
		SourceURL:         "https://huggingface.co/ggml-org/gemma-4-26B-A4B-it-GGUF/resolve/bb4531cda34d1ea09d9814959ed4d5833cf2a4c8/gemma-4-26B-A4B-it-Q4_0.gguf",
		SizeBytes:         14_618_145_824,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gemma4",
		DisplayLabel:      "Gemma 4 26B-A4B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 32,
		Notes:             "MoE",
	},
	// ── Microsoft Phi 4 ──────────────────────────────────────────────────────
	"phi-4-mini": {
		Name:              "phi-4-mini",
		SourceURL:         "https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf",
		SizeBytes:         2_491_874_688,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "phi-4",
		DisplayLabel:      "Phi-4 Mini",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
	},
	// ── DeepSeek ──────────────────────────────────────────────────────────────
	"deepseek-r1-0528-qwen3-8b": {
		Name:              "deepseek-r1-0528-qwen3-8b",
		SourceURL:         "https://huggingface.co/bartowski/deepseek-ai_DeepSeek-R1-0528-Qwen3-8B-GGUF/resolve/main/deepseek-ai_DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf",
		SizeBytes:         5_027_783_040,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "deepseek",
		DisplayLabel:      "DeepSeek R1 0528 (Qwen3 8B distill)",
		UseCase:           useCaseReasoning,
		RecommendedVRAMGB: 8,
	},
	"deepseek-r1-distill-qwen-7b": {
		Name:              "deepseek-r1-distill-qwen-7b",
		SourceURL:         "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
		SizeBytes:         4_683_073_504,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		ReasoningProtocol: reasoningProtocolLlamaCommonChat,
		ReasoningFormat:   reasoningFormatDeepSeek,
		Family:            "deepseek",
		DisplayLabel:      "DeepSeek R1 Distill Qwen 7B",
		UseCase:           useCaseReasoning,
		RecommendedVRAMGB: 8,
	},
	// ── Coding-specialized GGUFs ─────────────────────────────────────────────
	"starcoder2-7b-instruct": {
		Name:              "starcoder2-7b-instruct",
		SourceURL:         "https://huggingface.co/QuantFactory/starcoder2-7b-instruct-GGUF/resolve/main/starcoder2-7b-instruct.Q4_K_M.gguf",
		SizeBytes:         4_461_280_480,
		Curated:           true,
		Family:            "starcoder2",
		DisplayLabel:      "StarCoder2 7B Instruct",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 8,
		Notes:             "code/FIM",
	},
	"deepseek-coder-v2-lite": {
		Name:              "deepseek-coder-v2-lite",
		SourceURL:         "https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF/resolve/main/DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf",
		SizeBytes:         10_364_416_768,
		Curated:           true,
		Family:            "deepseek-coder",
		DisplayLabel:      "DeepSeek Coder V2 Lite",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 24,
		Notes:             "MoE coding",
	},
	"codestral-22b": {
		Name:              "codestral-22b",
		SourceURL:         "https://huggingface.co/bartowski/Codestral-22B-v0.1-GGUF/resolve/main/Codestral-22B-v0.1-Q4_K_M.gguf",
		SizeBytes:         13_341_237_600,
		Curated:           true,
		Family:            "codestral",
		DisplayLabel:      "Codestral 22B",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 24,
		Notes:             "code/FIM; license-restricted",
	},
	"devstral-small-2507": {
		Name:              "devstral-small-2507",
		SourceURL:         "https://huggingface.co/mistralai/Devstral-Small-2507_gguf/resolve/main/Devstral-Small-2507-Q4_K_M.gguf",
		SizeBytes:         14_333_915_904,
		Curated:           true,
		Family:            "devstral",
		DisplayLabel:      "Devstral Small 2507",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 24,
		Notes:             "agentic coding",
	},
	// ── OpenAI open-weight ───────────────────────────────────────────────────
	"gpt-oss-20b": {
		Name:              "gpt-oss-20b",
		SourceURL:         "https://huggingface.co/ggml-org/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-mxfp4.gguf",
		SizeBytes:         12_109_566_560,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "gpt-oss",
		DisplayLabel:      "GPT-OSS 20B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 24,
	},
	// ── IBM Granite 3.2 ──────────────────────────────────────────────────────
	"granite-3.2-2b": {
		Name:              "granite-3.2-2b",
		SourceURL:         "https://huggingface.co/bartowski/ibm-granite_granite-3.2-2b-instruct-GGUF/resolve/main/ibm-granite_granite-3.2-2b-instruct-Q4_K_M.gguf",
		SizeBytes:         1_545_296_512,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "granite",
		DisplayLabel:      "IBM Granite 3.2 2B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
	},
	"granite-3.2-8b": {
		Name:              "granite-3.2-8b",
		SourceURL:         "https://huggingface.co/bartowski/ibm-granite_granite-3.2-8b-instruct-GGUF/resolve/main/ibm-granite_granite-3.2-8b-instruct-Q4_K_M.gguf",
		SizeBytes:         4_942_859_808,
		Curated:           true,
		ToolProtocol:      toolProtocolLlamaCommonChat,
		Family:            "granite",
		DisplayLabel:      "IBM Granite 3.2 8B",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
	},
	// ── OpenVINO IR (served by modeld in openvino mode) ───────────────────────
	// Multi-file IR repos pulled over the HF Hub HTTP API into models/openvino/.
	"qwen2.5-coder-0.5b-ov": {
		Name:              "qwen2.5-coder-0.5b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen2.5-Coder-0.5B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen2.5-Coder-0.5B-Instruct-int4-ov",
		SizeBytes:         348_761_603,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen2.5-coder-ov",
		DisplayLabel:      "Qwen 2.5 Coder 0.5B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
		Notes:             "fastest smoke test",
	},
	"qwen2.5-coder-1.5b-ov": {
		Name:              "qwen2.5-coder-1.5b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen2.5-Coder-1.5B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen2.5-Coder-1.5B-Instruct-int4-ov",
		SizeBytes:         941_408_897,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen2.5-coder-ov",
		DisplayLabel:      "Qwen 2.5 Coder 1.5B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
		Notes:             "small coding model",
	},
	"qwen2.5-coder-3b-ov": {
		Name:              "qwen2.5-coder-3b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen2.5-Coder-3B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen2.5-Coder-3B-Instruct-int4-ov",
		SizeBytes:         1_835_241_153,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen2.5-coder-ov",
		DisplayLabel:      "Qwen 2.5 Coder 3B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 6,
	},
	"qwen2.5-coder-7b-ov": {
		Name:              "qwen2.5-coder-7b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen2.5-Coder-7B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen2.5-Coder-7B-Instruct-int4-ov",
		SizeBytes:         4_508_507_072,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen2.5-coder-ov",
		DisplayLabel:      "Qwen 2.5 Coder 7B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 8,
		Notes:             "coding default",
	},
	"qwen2.5-coder-14b-ov": {
		Name:              "qwen2.5-coder-14b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen2.5-Coder-14B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen2.5-Coder-14B-Instruct-int4-ov",
		SizeBytes:         8_453_145_650,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen2.5-coder-ov",
		DisplayLabel:      "Qwen 2.5 Coder 14B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 16,
	},
	"tinyllama-1.1b-chat-v1.0-int4-ov": {
		Name:              "tinyllama-1.1b-chat-v1.0-int4-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/TinyLlama-1.1B-Chat-v1.0-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/TinyLlama-1.1B-Chat-v1.0-int4-ov",
		SizeBytes:         636_000_000,
		Curated:           true,
		Family:            "tinyllama-ov",
		DisplayLabel:      "TinyLlama 1.1B Chat (OpenVINO)",
		UseCase:           useCaseSmoke,
		RecommendedVRAMGB: 6,
	},
	"phi-4-mini-ov": {
		AgenticTier:      AgenticTierNone,
		AgenticEvidence:  "chat template carries no tool-call markers, so the runtime cannot read a call from it at all",
		AutoContextLimit: 4096, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 32, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Origin: "us", ReleasedAt: "2025-02-26", License: "mit", AutoEligible: true,
		Name:              "phi-4-mini-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Phi-4-mini-instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Phi-4-mini-instruct-int4-ov",
		SizeBytes:         2388943800,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "phi-4-ov",
		DisplayLabel:      "Phi-4 Mini (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
	},
	"qwen3-4b-ov": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "official BFCL v4 multi-turn 22.12%",
		AutoContextLimit: 40960, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 36, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Origin: "china", ReleasedAt: "2025-04-29", License: "apache-2.0", AutoEligible: true,
		Name:              "qwen3-4b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen3-4B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen3-4B-int4-ov",
		SizeBytes:         2290768181,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen3-ov",
		DisplayLabel:      "Qwen 3 4B (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 6,
	},
	"qwen3-8b-ov": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "official BFCL v4 multi-turn 41.75%",
		AutoContextLimit: 40960, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 36, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Origin: "china", ReleasedAt: "2025-04-29", License: "apache-2.0", AutoEligible: true,
		Name:              "qwen3-8b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen3-8B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen3-8B-int4-ov",
		SizeBytes:         4882865352,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen3-ov",
		DisplayLabel:      "Qwen 3 8B (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
	},
	"qwen3-14b-ov": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "Qwen3 tool-trained family; official BFCL v4 rows exist for this generation",
		AutoContextLimit: 40960, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 40, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 4096},
		Origin: "china", ReleasedAt: "2025-04-29", License: "apache-2.0", AutoEligible: true,
		Name:              "qwen3-14b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen3-14B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen3-14B-int4-ov",
		SizeBytes:         9731519596,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen3-ov",
		DisplayLabel:      "Qwen 3 14B (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 16,
	},
	"qwen3-30b-ov": {
		Name:              "qwen3-30b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen3-30B-A3B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen3-30B-A3B-int4-ov",
		SizeBytes:         16_344_043_009,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen3-ov",
		DisplayLabel:      "Qwen 3 30B-A3B (OpenVINO)",
		UseCase:           useCaseReasoning,
		RecommendedVRAMGB: 32,
		Notes:             "MoE",
	},
	"qwen3-coder-30b-a3b-ov": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "30B-A3B coding MoE served through the Qwen tool template",
		AutoContextLimit: 262144, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 48, WindowedLayers: 0, Window: 0, PerLayerKVBytes: 2048},
		Origin: "china", ReleasedAt: "2025-07-22", License: "apache-2.0", AutoEligible: true,
		Name:              "qwen3-coder-30b-a3b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/Qwen3-Coder-30B-A3B-Instruct-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/Qwen3-Coder-30B-A3B-Instruct-int4-ov",
		SizeBytes:         16344057522,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "qwen3-coder-ov",
		DisplayLabel:      "Qwen 3 Coder 30B-A3B (OpenVINO)",
		UseCase:           useCaseCoding,
		RecommendedVRAMGB: 32,
		Notes:             "MoE",
	},
	"deepseek-r1-distill-qwen-7b-ov": {
		Name:              "deepseek-r1-distill-qwen-7b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/DeepSeek-R1-Distill-Qwen-7B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/DeepSeek-R1-Distill-Qwen-7B-int4-ov",
		SizeBytes:         4_503_931_427,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "deepseek-ov",
		DisplayLabel:      "DeepSeek R1 Distill Qwen 7B (OpenVINO)",
		UseCase:           useCaseReasoning,
		RecommendedVRAMGB: 8,
	},
	"gpt-oss-20b-ov": {
		AgenticTier:      AgenticTierAgentic,
		AgenticEvidence:  "agentic tool use with sliding attention on half the layers (24 KiB per token of KV)",
		AutoContextLimit: 131072, AutoKVProfile: capacity.LayerKVProfile{GlobalLayers: 12, WindowedLayers: 12, Window: 128, PerLayerKVBytes: 2048},
		Origin: "us", ReleasedAt: "2025-08-05", License: "apache-2.0", AutoEligible: true,
		Name:              "gpt-oss-20b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/gpt-oss-20b-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/gpt-oss-20b-int4-ov",
		SizeBytes:         12623951367,
		Curated:           true,
		ToolProtocol:      toolProtocolOpenVINOJSONSchemaToolCalls,
		Family:            "gpt-oss-ov",
		DisplayLabel:      "GPT-OSS 20B (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 24,
	},
	// Multimodal (text+image): served by modeld's OpenVINO GenAI VLM pipeline.
	// The snapshot pull fetches every repo file, including the vision encoder
	// (openvino_vision_embeddings_model.*). Repo existence, file list, and total
	// size verified against the HF API on 2026-07-22. No ToolProtocol: the VLM
	// pipeline is not certified for tool calls yet.
	"gemma4-e4b-ov": {
		Name:              "gemma4-e4b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/gemma-4-E4B-it-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/gemma-4-E4B-it-int4-ov",
		SizeBytes:         6_459_790_168,
		Curated:           true,
		Family:            "gemma4-ov",
		DisplayLabel:      "Gemma 4 E4B (OpenVINO)",
		UseCase:           useCaseChat,
		RecommendedVRAMGB: 8,
		Vision:            true,
		Notes:             "needs ~7GB+ free memory",
	},
	// Smallest curated vision model: verified end-to-end in the OpenVINO VLM
	// cell. The tier for trying image input on small CPU/iGPU machines where
	// the Gemma 4 snapshot does not fit.
	"internvl2-1b-ov": {
		Name:              "internvl2-1b-ov",
		Backend:           "openvino",
		Repo:              "OpenVINO/InternVL2-1B-int4-ov",
		SourceURL:         "https://huggingface.co/OpenVINO/InternVL2-1B-int4-ov",
		SizeBytes:         798_470_894,
		Curated:           true,
		Family:            "internvl2-ov",
		DisplayLabel:      "InternVL2 1B (OpenVINO)",
		UseCase:           useCaseSmoke,
		RecommendedVRAMGB: 6,
		Vision:            true,
		Notes:             "smallest vision model",
	},
}

type familyMapping struct {
	CanonicalName string
	Substrings    []string
}

var defaultFamilies = []familyMapping{
	// OpenVINO aliases first so backend-specific repo ids keep the -ov target.
	{CanonicalName: "qwen2.5-coder-14b-ov", Substrings: []string{"openvino/qwen2.5-coder-14", "qwen2.5-coder-14b-instruct-int4-ov", "qwen2.5-coder-14b-ov"}},
	{CanonicalName: "qwen2.5-coder-7b-ov", Substrings: []string{"openvino/qwen2.5-coder-7", "qwen2.5-coder-7b-instruct-int4-ov", "qwen2.5-coder-7b-ov"}},
	{CanonicalName: "qwen2.5-coder-3b-ov", Substrings: []string{"openvino/qwen2.5-coder-3", "qwen2.5-coder-3b-instruct-int4-ov", "qwen2.5-coder-3b-ov"}},
	{CanonicalName: "qwen2.5-coder-1.5b-ov", Substrings: []string{"openvino/qwen2.5-coder-1.5", "qwen2.5-coder-1.5b-instruct-int4-ov", "qwen2.5-coder-1.5b-ov"}},
	{CanonicalName: "qwen2.5-coder-0.5b-ov", Substrings: []string{"openvino/qwen2.5-coder-0.5", "qwen2.5-coder-0.5b-instruct-int4-ov", "qwen2.5-coder-0.5b-ov"}},
	{CanonicalName: "tinyllama-1.1b-chat-v1.0-int4-ov", Substrings: []string{"openvino/tinyllama-1.1b-chat-v1.0-int4-ov", "tinyllama-1.1b-chat-v1.0-int4-ov"}},
	{CanonicalName: "qwen3-coder-30b-a3b-ov", Substrings: []string{"openvino/qwen3-coder-30", "qwen3-coder-30b-a3b-instruct-int4-ov", "qwen3-coder-30b-a3b-ov"}},
	{CanonicalName: "qwen3-30b-ov", Substrings: []string{"openvino/qwen3-30", "qwen3-30b-a3b-int4-ov", "qwen3-30b-ov"}},
	{CanonicalName: "qwen3-14b-ov", Substrings: []string{"openvino/qwen3-14", "qwen3-14b-int4-ov", "qwen3-14b-ov"}},
	{CanonicalName: "qwen3-8b-ov", Substrings: []string{"openvino/qwen3-8", "qwen3-8b-int4-ov", "qwen3-8b-ov"}},
	{CanonicalName: "qwen3-4b-ov", Substrings: []string{"openvino/qwen3-4", "qwen3-4b-int4-ov", "qwen3-4b-ov"}},
	{CanonicalName: "phi-4-mini-ov", Substrings: []string{"openvino/phi-4-mini", "phi-4-mini-instruct-int4-ov", "phi-4-mini-ov"}},
	// Gemma 4 OpenVINO alias before the llama gemma mappings: the "gemma-4"/
	// "gemma" catch-alls below would otherwise route the multimodal OV repo id
	// to the llama text entry.
	{CanonicalName: "gemma4-e4b-ov", Substrings: []string{"openvino/gemma-4-e4b", "gemma-4-e4b-it-int4-ov", "gemma4-e4b-ov"}},
	{CanonicalName: "internvl2-1b-ov", Substrings: []string{"openvino/internvl2-1b", "internvl2-1b-int4-ov", "internvl2-1b-ov", "internvl2", "internvl"}},
	{CanonicalName: "deepseek-r1-distill-qwen-7b-ov", Substrings: []string{"openvino/deepseek-r1-distill-qwen-7", "deepseek-r1-distill-qwen-7b-int4-ov", "deepseek-r1-distill-qwen-7b-ov"}},
	{CanonicalName: "gpt-oss-20b-ov", Substrings: []string{"openvino/gpt-oss-20b", "gpt-oss-20b-int4-ov", "gpt-oss-20b-ov"}},
	// Qwen 3 (checked before 2.5 to avoid substring collision).
	{CanonicalName: "qwen3-coder-30b-a3b", Substrings: []string{"qwen3-coder-30", "qwen3-coder", "qwen-coder"}},
	{CanonicalName: "qwen3-30b", Substrings: []string{"qwen3-30", "qwen3:30"}},
	{CanonicalName: "qwen3-14b", Substrings: []string{"qwen3-14", "qwen3:14"}},
	{CanonicalName: "qwen3-8b", Substrings: []string{"qwen3-8", "qwen3:8"}},
	{CanonicalName: "qwen3-4b", Substrings: []string{"qwen3-4", "qwen3:4"}},
	{CanonicalName: "qwen3-8b", Substrings: []string{"qwen3"}},
	// Coding-specialized models.
	{CanonicalName: "qwen2.5-coder-32b", Substrings: []string{"qwen2.5-coder-32", "qwen25-coder-32", "qwen2.5-coder:32"}},
	{CanonicalName: "qwen2.5-coder-14b", Substrings: []string{"qwen2.5-coder-14", "qwen25-coder-14", "qwen2.5-coder:14"}},
	{CanonicalName: "qwen2.5-coder-7b", Substrings: []string{"qwen2.5-coder-7", "qwen25-coder-7", "qwen2.5-coder:7"}},
	{CanonicalName: "qwen2.5-coder-3b", Substrings: []string{"qwen2.5-coder-3", "qwen25-coder-3", "qwen2.5-coder:3"}},
	{CanonicalName: "qwen2.5-coder-1.5b", Substrings: []string{"qwen2.5-coder-1.5", "qwen25-coder-1.5", "qwen2.5-coder:1.5"}},
	{CanonicalName: "qwen2.5-coder-0.5b", Substrings: []string{"qwen2.5-coder-0.5", "qwen25-coder-0.5", "qwen2.5-coder"}},
	{CanonicalName: "devstral-small-2507", Substrings: []string{"devstral-small-2507", "devstral-small", "devstral"}},
	{CanonicalName: "codestral-22b", Substrings: []string{"codestral-22", "codestral"}},
	{CanonicalName: "deepseek-coder-v2-lite", Substrings: []string{"deepseek-coder-v2-lite", "deepseek-coder-v2", "deepseek-coder"}},
	{CanonicalName: "starcoder2-7b-instruct", Substrings: []string{"starcoder2-7b-instruct", "starcoder2-7", "starcoder2"}},
	// Gemma 4.
	{CanonicalName: "gemma4-26b-a4b", Substrings: []string{"gemma-4-26", "gemma4-26", "gemma4:26"}},
	{CanonicalName: "gemma4-12b", Substrings: []string{"gemma-4-12", "gemma4-12", "gemma4:12"}},
	{CanonicalName: "gemma4-e2b", Substrings: []string{"gemma-4-e2", "gemma4-e2", "gemma4:e2"}},
	{CanonicalName: "gemma4-e4b", Substrings: []string{"gemma-4-e4", "gemma4-e4", "gemma4:e4", "gemma-4", "gemma4", "gemma"}},
	// Phi 4.
	{CanonicalName: "phi-4-mini", Substrings: []string{"phi-4-mini", "phi4-mini", "phi4mini", "phi-4", "phi4"}},
	// DeepSeek.
	{CanonicalName: "deepseek-r1-0528-qwen3-8b", Substrings: []string{"deepseek-r1-0528", "deepseek-r1-qwen3", "deepseek-r1", "deepseek"}},
	// OpenAI open-weight.
	{CanonicalName: "gpt-oss-20b", Substrings: []string{"openai/gpt-oss-20b", "openai_gpt-oss-20b", "gpt-oss-20b", "gpt-oss", "openai-oss", "openai oss"}},
	// Granite.
	{CanonicalName: "granite-3.2-8b", Substrings: []string{"granite-3.2-8", "granite-3.1", "granite3.", "granite"}},
}

const defaultFallback = "qwen3-4b"
